apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserverchat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: tazhibayda/tcpserverchat:latest
          ports:
            - containerPort: 8000
            - containerPort: 9090
            - containerPort: 6060
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
