name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: go-version: '1.22'
      - run: go mod download
      - run: go fmt ./...
      - run: go vet ./...
      - run: go test ./... -race -coverprofile=coverage.out
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest

  deploy_to_k8s:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            deploy/deployment.yaml
            deploy/service.yaml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest
